import { Roboto_Flex } from "next/font/google";
import "./globals.css";

const rf = Roboto_Flex({ subsets: ["latin","greek"] ,axes:['wdth','XTRA']});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rf.className}>{children}</body>
    </html>
  );
}
